---
deployment:
      tasks:
        - export DEPLOYPATH=/home/pand2970/public_html  # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH